[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/equipe/etienne-mineur/index.html"
to = "/personnes/etienne-mineur/"

[[redirects]]
from = "/equipe/equipe-editoriale/index.html"
to = "/personnes/equipe-editoriale/"

[[redirects]]
from = "/actualites/mastodon/index.html"
to = "/actualites/travaux-en-cours/mastodon/"

[[redirects]]
from = "/actualites/2023-02-09-visual-culture-open-source-publishing-git-et-le-design-graphique/index.html"
to = "/actualites/2014-11-01-visual-culture-open-source-publishing-git-et-le-design-graphique/"

[[redirects]]
from = "/actualites/2023-01-19-recherche-utilisateur-mastodon/index.html"
to = "/actualites/2021-01-08-recherche-utilisateur-mastodon/"

[[redirects]]
from = "/equipe/arnaud-levy/index.html"
to = "/personnes/arnaud-levy/"

[[redirects]]
from = "/actualites/2023-01-17-peertube-etude-des-usages-et-amelioration-de-l-utilisabilite-marie-cecile-godwin/index.html"
to = "/actualites/2022-02-16-peertube-etude-des-usages-et-amelioration-de-l-utilisabilite-marie-cecile-godwin/"

[[redirects]]
from = "/actualites/2023-04-10-open-source-experimental-and-tiny-tools-roundup/index.html"
to = "/actualites/2023-04-10-tiny-directory/"

[[redirects]]
from = "/communs-numeriques/peertube/index.html"
to = "/communs-numeriques/travaux-en-cours/peertube/"

[[redirects]]
from = "/organisations/res-numerica/index.html"
to = "/organisations/resnumerica/"

[[redirects]]
from = "/actualites/2023-01-19-recherche-utilisateur-mobilizon-marie-cecile-godwin/index.html"
to = "/actualites/2021-01-08-recherche-utilisateur-mobilizon-marie-cecile-godwin/"

[[redirects]]
from = "/actualites/2023-01-19-recherche-utilisateur-pixelfed-marie-cecile-godwin/index.html"
to = "/actualites/2021-01-08-recherche-utilisateur-pixelfed-marie-cecile-godwin/"

[[redirects]]
from = "/actualites/communs/peertube/index.html"
to = "/actualites/travaux-en-cours/peertube/"

[[redirects]]
from = "/initiatives/peertube/index.html"
to = "/communs-numeriques/travaux-en-cours/peertube/"

[[redirects]]
from = "/organisations/institutdesign/index.html"
to = "/organisations/institut-superieur-de-design-de-saint-malo/"

[[redirects]]
from = "/actualites/2023-01-08-recherche-utilisateur-pixelfed-marie-cecile-godwin/index.html"
to = "/actualites/2021-01-08-recherche-utilisateur-pixelfed-marie-cecile-godwin/"

[[redirects]]
from = "/actualites/2022/12/26/lancement-de-linitiative/index.html"
to = "/actualites/2022-12-26-lancement-de-linitiative/"

[[redirects]]
from = "/equipe/index.html"
to = "/personnes/"

[[redirects]]
from = "/actualites/2023-01-19-recherche-utilisateur-mastodon-marie-cecile-godwin/index.html"
to = "/actualites/2021-01-08-recherche-utilisateur-mastodon-marie-cecile-godwin/"

[[redirects]]
from = "/equipe/arnaud-levy/actualites/index.html"
to = "/personnes/arnaud-levy/actualites/"

[[redirects]]
from = "/actualites/open-food-facts/index.html"
to = "/actualites/travaux-en-cours/open-food-facts/"

[[redirects]]
from = "/actualites/peertube/index.html"
to = "/actualites/travaux-en-cours/peertube/"

